DROP TABLE IF EXISTS DOMICILIOS;
CREATE TABLE DOMICILIOS (
ID INT AUTO_INCREMENT PRIMARY KEY,
CALLE VARCHAR(50) NOT NULL,
NUMERO INT NOT NULL,
LOCALIDAD VARCHAR(50) NOT NULL,
PROVINCIA VARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS PACIENTES;
CREATE TABLE PACIENTES (
ID INT AUTO_INCREMENT PRIMARY KEY,
APELLIDO VARCHAR(50) NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
DNI VARCHAR(50) NOT NULL,
FECHA_INGRESO DATE NOT NULL,
ID_DOMICILIO INT
);

DROP TABLE IF EXISTS ODONTOLOGOS;
CREATE TABLE ODONTOLOGOS (
ID INT AUTO_INCREMENT PRIMARY KEY,
IDMATRICULA VARCHAR(50) NOT NULL,
NOMBRES VARCHAR(50) NOT NULL,
APELLIDOS VARCHAR(50) NOT NULL
);

INSERT INTO DOMICILIOS VALUES (DEFAULT, 'CALLE SIEMPRE VIVA', 123, 'SAN PEDRO', 'JUJUY');

INSERT INTO PACIENTES VALUES (DEFAULT, 'COSMO', 'FULANITO', '123456', '2024-02-15', 1);

INSERT INTO ODONTOLOGOS VALUES (DEFAULT, 'MR1234', 'CARLOS', 'PEREZ');

INSERT INTO ODONTOLOGOS VALUES (DEFAULT, 'JDS146', 'MARTIN', 'DE FRANCISCO');